"""Q4: sort the edit lines, and every .py file in the repo, into junk buckets.

Each file gets the first bucket that matches, in this order:
  vendored             a copy of an outside package: a vendor/ folder, or django/utils/six.py
  generated            the first 5 lines say the file is generated, or not to be edited
  migrations           the file defines a top-level `class Migration(migrations.Migration)`, which is
                       how Django itself spots one. File names don't work: tests have migrations
                       named 1_auto.py, and tests/migrations/ also holds ordinary test files
  django/conf/locale/, docs/, tests/   by path
  other                everything else (in practice django/ itself, setup.py, scripts/)

Also lists the non-.py files that mention the old names, and whether c651331b34 changed them.

Reads results/sites_279.csv. Writes:
  results/junk_buckets.csv           one row per edit line, with its bucket
  results/junk_non_py_mentions.csv   non-.py files that mention the old names
  results/junk_buckets_summary.json  counts per bucket, for the edit set and the whole repo

Usage: python scripts/q4_junk_buckets.py [path-to-django]
"""
import csv
import json
import os
import re
import subprocess
import sys
from collections import Counter

import tree_sitter_python as tspython
from tree_sitter import Language, Parser

REPO = os.path.expanduser(sys.argv[1] if len(sys.argv) > 1 else "~/MLOps/data/django")
EXPECTED_COMMIT = "4353640ea9495d58fabd0357253b82de3b069408"
CONVERSION_COMMIT = "c651331b34"
BUCKETS = ["vendored", "generated", "migrations", "django/conf/locale/", "docs/", "tests/", "other"]
VENDORED_FILES = {"django/utils/six.py"}   # the outside `six` package, copied in (Copyright Benjamin Peterson)
GENERATED = re.compile(r"auto-?generated|generated by|do not edit|this file (is|was) generated", re.IGNORECASE)
OLD_NAMES = re.compile(r"(?<![A-Za-z0-9_])un?gettext(_lazy|_noop)?(?![A-Za-z0-9_])")


def git(*args):
    return subprocess.check_output(["git", "-C", REPO, *args], text=True)


def defines_migration(tree):
    """True if the module defines `class Migration(migrations.Migration)` at top level.

    Text inside strings doesn't count (the template in django/db/migrations/writer.py), and the
    superclass must be a Migration, so Django's own base class in migration.py doesn't count either.
    """
    for node in tree.root_node.children:
        if node.type == "decorated_definition":
            node = node.child_by_field_name("definition")
        if node is not None and node.type == "class_definition":
            bases = node.child_by_field_name("superclasses")
            if node.child_by_field_name("name").text == b"Migration" and bases is not None and b"Migration" in bases.text:
                return True
    return False


def bucket(rel, source, tree):
    if rel in VENDORED_FILES or "/vendor/" in "/" + rel:
        return "vendored"
    head = "\n".join(source.decode("utf-8", errors="replace").splitlines()[:5])
    if GENERATED.search(head):
        return "generated"
    if defines_migration(tree):
        return "migrations"
    for prefix in ("django/conf/locale/", "docs/", "tests/"):
        if rel.startswith(prefix):
            return prefix
    return "other"


def find_py_files(repo):
    files = []
    for root, dirs, names in os.walk(repo):
        dirs[:] = [d for d in dirs if d != ".git"]
        files += [os.path.join(root, n) for n in names if n.endswith(".py")]
    return sorted(files)


def count(rows, key):
    """Counts per bucket, in bucket order, zeros included."""
    got = Counter(key(r) for r in rows)
    return {b: got[b] for b in BUCKETS}


def main():
    commit = git("rev-parse", "HEAD").strip()
    if commit != EXPECTED_COMMIT:
        sys.exit(f"Wrong snapshot: {commit}. Run: git -C {REPO} checkout 4353640ea9")

    # Every .py file in the repo, with its bucket
    parser = Parser(Language(tspython.language()))
    file_bucket = {}
    named_like_migration = 0   # migration files that also have a 0001_name.py style name
    for path in find_py_files(REPO):
        with open(path, "rb") as fh:
            source = fh.read()
        rel = os.path.relpath(path, REPO)
        file_bucket[rel] = bucket(rel, source, parser.parse(source))
        if file_bucket[rel] == "migrations" and re.match(r"\d{4}_", os.path.basename(rel)):
            named_like_migration += 1

    # The edit lines, with the bucket of their file
    with open("results/sites_279.csv", newline="") as fh:
        edit = list(csv.DictReader(fh))
    for row in edit:
        row["bucket"] = file_bucket[row["file"]]

    os.makedirs("results", exist_ok=True)
    with open("results/junk_buckets.csv", "w", newline="") as fh:
        writer = csv.writer(fh, lineterminator="\n")
        writer.writerow(["file", "line", "kind", "bucket", "symbol", "text"])
        for r in edit:
            writer.writerow([r["file"], r["line"], r["kind"], r["bucket"], r["symbol"], r["text"]])

    # Non-.py files that mention the old names: docs, sample code, ...
    tracked = [f for f in git("ls-files", "-z").split("\0") if f]   # -z: names with non-ASCII characters come unquoted
    changed = {f.strip() for f in git("show", "--name-only", "-z", "--format=", CONVERSION_COMMIT).split("\0")} - {""}
    non_py = []
    for rel in tracked:
        if rel.endswith(".py"):
            continue
        with open(os.path.join(REPO, rel), "rb") as fh:
            data = fh.read()
        if b"\0" in data:   # binary: .mo, images, fonts
            continue
        hits = sum(1 for line in data.decode("utf-8", errors="replace").splitlines() if OLD_NAMES.search(line))
        if hits:
            non_py.append([rel, hits, "yes" if rel in changed else "no"])

    with open("results/junk_non_py_mentions.csv", "w", newline="") as fh:
        writer = csv.writer(fh, lineterminator="\n")
        writer.writerow(["file", "lines_mentioning", "changed_by_commit"])
        writer.writerows(non_py)

    types = Counter(os.path.splitext(f)[1] or "(none)" for f in tracked)
    top_types = dict(types.most_common(8))
    top_types["everything else"] = len(tracked) - sum(top_types.values())

    migration_files = [f for f, b in file_bucket.items() if b == "migrations"]
    summary = {
        "commit": commit,
        "bucket_order": BUCKETS,
        "edit_lines": {
            "total": len(edit),
            "by_bucket": count(edit, lambda r: r["bucket"]),
            "files_by_bucket": count({r["file"]: r for r in edit}.values(), lambda r: r["bucket"]),
            "in_a_migrations_folder_but_not_a_migration": sorted(
                {r["file"] for r in edit if "migrations" in r["file"] and r["bucket"] != "migrations"}),
        },
        "repo_py_files": {
            "total": len(file_bucket),
            "by_bucket": count(file_bucket.values(), lambda b: b),
        },
        "migration_files": {
            "total": len(migration_files),
            "in_tests": sum(1 for f in migration_files if f.startswith("tests/")),
            "named_like_0001_name": named_like_migration,
        },
        "vendored_files": sorted(f for f, b in file_bucket.items() if b == "vendored"),
        "generated_files": sorted(f for f, b in file_bucket.items() if b == "generated"),
        "non_py_mentions": {
            "files": len(non_py),
            "lines": sum(r[1] for r in non_py),
            "files_changed_by_commit": sum(1 for r in non_py if r[2] == "yes"),
        },
        "tracked_files": {"total": len(tracked), "by_type": top_types},
    }
    with open("results/junk_buckets_summary.json", "w") as fh:
        json.dump(summary, fh, indent=2)
        fh.write("\n")

    print(f"commit: {commit}")
    print(f"edit lines: {len(edit)} in {len({r['file'] for r in edit})} files")
    for b in BUCKETS:
        print(f"  {b:<20} {summary['edit_lines']['by_bucket'][b]:>4} lines"
              f"   {summary['edit_lines']['files_by_bucket'][b]:>4} files"
              f"   (repo: {summary['repo_py_files']['by_bucket'][b]} .py files)")
    print(f"migration files: {len(migration_files)}, {summary['migration_files']['in_tests']} of them in tests/, "
          f"{named_like_migration} named like 0001_name.py")
    print(f"vendored .py files: {summary['vendored_files']}")
    print(f"generated .py files: {summary['generated_files']}")
    print(f"non-.py files mentioning the old names: {len(non_py)} files, {summary['non_py_mentions']['lines']} lines, "
          f"{summary['non_py_mentions']['files_changed_by_commit']} changed by {CONVERSION_COMMIT}")
    print("saved results/junk_buckets.csv, junk_non_py_mentions.csv, junk_buckets_summary.json")


if __name__ == "__main__":
    main()
