"""Shared: the curated removed deprecations (regex = a USE of the symbol). Dates verified against code_deprecations.csv / PR history.
dep = first commit that made it warn (report/DeprecatedConstant), rem = commit that deleted it from homeassistant/."""
R = "data/repo"
SC = "data/code"
SNAP = "75c314edf0013bff046106015ab6cfb0b8c6b452"
HERE = "."
UNITS = "POWER_VOLT_AMPERE|POWER_WATT|POWER_KILO_WATT|POWER_BTU_PER_HOUR|ENERGY_KILO_WATT_HOUR|ENERGY_MEGA_WATT_HOUR|ENERGY_WATT_HOUR|ELECTRIC_CURRENT_MILLIAMPERE|ELECTRIC_CURRENT_AMPERE|ELECTRIC_POTENTIAL_MILLIVOLT|ELECTRIC_POTENTIAL_VOLT|TIME_MICROSECONDS|TIME_MILLISECONDS|TIME_SECONDS|TIME_MINUTES|TIME_HOURS|TIME_DAYS|TIME_WEEKS|TIME_MONTHS|TIME_YEARS|LENGTH_MILLIMETERS|LENGTH_CENTIMETERS|LENGTH_METERS|LENGTH_KILOMETERS|LENGTH_INCHES|LENGTH_FEET|LENGTH_YARD|LENGTH_MILES|FREQUENCY_HERTZ|FREQUENCY_KILOHERTZ|FREQUENCY_MEGAHERTZ|FREQUENCY_GIGAHERTZ|PRESSURE_PA|PRESSURE_HPA|PRESSURE_KPA|PRESSURE_BAR|PRESSURE_CBAR|PRESSURE_MBAR|PRESSURE_MMHG|PRESSURE_INHG|PRESSURE_PSI|SOUND_PRESSURE_DB|SOUND_PRESSURE_WEIGHTED_DBA|VOLUME_LITERS|VOLUME_MILLILITERS|VOLUME_CUBIC_METERS|VOLUME_CUBIC_FEET|VOLUME_GALLONS|VOLUME_FLUID_OUNCE|VOLUME_FLOW_RATE_CUBIC_METERS_PER_HOUR|VOLUME_FLOW_RATE_CUBIC_FEET_PER_MINUTE|MASS_GRAMS|MASS_KILOGRAMS|MASS_MILLIGRAMS|MASS_MICROGRAMS|MASS_OUNCES|MASS_POUNDS|IRRADIATION_WATTS_PER_SQUARE_METER|IRRADIATION_BTUS_PER_HOUR_SQUARE_FOOT|PRECIPITATION_INCHES|PRECIPITATION_MILLIMETERS|PRECIPITATION_MILLIMETERS_PER_HOUR|PRECIPITATION_INCHES_PER_HOUR|SPEED_FEET_PER_SECOND|SPEED_METERS_PER_SECOND|SPEED_KILOMETERS_PER_HOUR|SPEED_KNOTS|SPEED_MILES_PER_HOUR|SPEED_MILLIMETERS_PER_DAY|SPEED_INCHES_PER_DAY|SPEED_INCHES_PER_HOUR|DATA_BITS|DATA_KILOBITS|DATA_MEGABITS|DATA_GIGABITS|DATA_BYTES|DATA_KILOBYTES|DATA_MEGABYTES|DATA_GIGABYTES|DATA_TERABYTES|DATA_PETABYTES|DATA_EXABYTES|DATA_ZETTABYTES|DATA_YOTTABYTES|DATA_KIBIBYTES|DATA_MEBIBYTES|DATA_GIBIBYTES|DATA_TEBIBYTES|DATA_PEBIBYTES|DATA_EXBIBYTES|DATA_ZEBIBYTES|DATA_YOBIBYTES|DATA_RATE_BITS_PER_SECOND|DATA_RATE_KILOBITS_PER_SECOND|DATA_RATE_MEGABITS_PER_SECOND|DATA_RATE_GIGABITS_PER_SECOND|DATA_RATE_BYTES_PER_SECOND|DATA_RATE_KILOBYTES_PER_SECOND|DATA_RATE_MEGABYTES_PER_SECOND|DATA_RATE_GIGABYTES_PER_SECOND|DATA_RATE_KIBIBYTES_PER_SECOND|DATA_RATE_MEBIBYTES_PER_SECOND|DATA_RATE_GIBIBYTES_PER_SECOND"
SPECS = {
 # name: (regex, dep_date, rem_date[, informal_dep]) informal = UnitOf* enums introduced, constants marked deprecated in comments only
 "unit_consts":        (rf"(?<![.\w])({UNITS})\b", "2024-01-04", "2024-11-28", "2022-10-26"),
 "TEMP_consts":        (r"(?<![.\w])TEMP_(CELSIUS|FAHRENHEIT|KELVIN)\b", "2024-01-04", "2024-11-28", "2022-10-26"),
 "async_setup_platforms": (r"\.async_setup_platforms\(", "2022-07-09", "2023-04-23"),
 "STATE_ALARM_consts": (r"\bSTATE_ALARM_[A-Z_]+\b", "2024-10-21", "2025-10-06"),
 "hass_helpers":       (r"\bhass\.helpers\.", "2024-03-31", "2025-04-23"),
 "RESULT_TYPE_consts": (r"\bRESULT_TYPE_[A-Z_]+\b", "2023-12-23", "2024-11-29"),
 "async_forward_entry_setup": (r"\.async_forward_entry_setup\(", "2024-06-04", "2025-05-09"),
 "async_get_registry": (r"\b(entity|device|area)_registry\.async_get_registry\(|\b(er|dr|ar)\.async_get_registry\(", "2022-05-18", "2023-04-23"),
}
